### ISSUE TITLE
Unknown package `pyutls`

### ISSUE THREAD

**Issue by DefiDebauchery** [cyrildever/merkle-trees#6]
https://github.com/cyrildever/merkle-trees/blob/6c1481fbd058a7c14872852db182fba214380f01/packages/py/src/merklepy/proof.py#L3

This doesn't seem to be a typo of the package `pyutils`, which does not have a `from_hash` method; I'm unsure what package this is supposed to reference.

**Comment by cyrildever** [comment]
My mistake: I've added the dependency in the latest update (`v1.2.9`).

In the meantime, if you don't upgrade, you should import the [`py-utls` module](https://pypi.org/project/py-utls/) from PyPi:
```console
$ pip install py-utls
```

But there's no `from_hash` method needed anyway... Only `from_hex`.
